- hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant

  tasks:
   - name: Actualizar sistema
     become: yes
     command: apt-get update
   - name: Instalar essential
     become: yes
     command: apt-get install -y build-essential
   - name: Instalar Git
     become: yes
     command: apt-get install -y git
   - name: Instalar pip
     become: yes
     command: apt-get install -y python3-pip
   - name: Actualizar pip
     become: yes
     command: pip3 install --upgrade pip
